//! The panel model's Swift types, generated from the Rust ones so the two
//! cannot drift. facet_generate writes the plain types; its own JSON mode
//! does not compile in Swift and Crux's generator is binary only (#254),
//! so `DecodablePlugin` adds an `init(from:)` to each type that reads
//! serde_json's default shapes, and a plain `JSONDecoder()` reads
//! `panel.json`. Decode only: the Swift side never writes the model.

mod decodable;

use std::io;

use cockpit_core::panel::Panel;
use facet_generate::generation::CodeGeneratorConfig;
use facet_generate::generation::swift::SwiftCodeGenerator;
use facet_generate::reflection::RegistryBuilder;

pub use decodable::DecodablePlugin;

/// The generated file's first line, so a reader knows not to edit it.
pub const HEADER: &str = "// Generated by native/typegen from the Rust panel model. Do not edit: run native/mac/test.sh or build.";

/// Why the Swift could not be written.
#[derive(Debug)]
pub enum Error {
    /// facet_generate could not reflect a type.
    Reflect(String),
    /// Writing the output failed.
    Io(io::Error),
    /// The generator wrote something other than UTF-8.
    Utf8(std::string::FromUtf8Error),
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Error::Reflect(e) => write!(f, "could not reflect the panel model: {e}"),
            Error::Io(e) => write!(f, "could not write the Swift: {e}"),
            Error::Utf8(e) => write!(f, "the Swift was not UTF-8: {e}"),
        }
    }
}

impl std::error::Error for Error {}

impl From<io::Error> for Error {
    fn from(e: io::Error) -> Self {
        Error::Io(e)
    }
}

/// The whole Swift file for the panel model: every type `Panel` reaches,
/// each with its `init(from:)`, then their `Decodable` conformances.
pub fn swift() -> Result<String, Error> {
    let registry = RegistryBuilder::new()
        .add_type::<Panel>()
        .and_then(RegistryBuilder::build)
        .map_err(|e| Error::Reflect(e.to_string()))?;
    let config = CodeGeneratorConfig::new("PanelTypes".to_string());
    let mut out = Vec::new();
    SwiftCodeGenerator::new(&config)
        .with_plugins(vec![std::sync::Arc::new(DecodablePlugin)])
        .output(&mut out, &registry)?;
    let body = String::from_utf8(out).map_err(Error::Utf8)?;
    // The Swift emitter skips the plugin's conformance hook, so the
    // conformances go after the types, where the `init(from:)` in each
    // type's body satisfies them.
    let conformances: String = registry
        .keys()
        .map(|name| format!("extension {}: Decodable {{}}\n", name.name))
        .collect();
    Ok(format!("{HEADER}\n\n{body}\n{conformances}"))
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Every type the panel reaches, as the Swift names them.
    const TYPES: [&str; 22] = [
        "Anchor",
        "Card",
        "Chip",
        "EditorView",
        "Icon",
        "Lane",
        "LaneKey",
        "MenuAction",
        "MenuItem",
        "MenuTarget",
        "MenuView",
        "Needs",
        "NeedsRow",
        "NextLine",
        "Panel",
        "PanelView",
        "Piece",
        "PillColors",
        "ProjectHead",
        "ProjectRow",
        "Row",
        "Token",
    ];

    fn generated() -> String {
        match swift() {
            Ok(s) => s,
            Err(e) => panic!("{e}"),
        }
    }

    #[test]
    fn every_type_the_panel_reaches_is_decodable() {
        let s = generated();
        for t in TYPES {
            assert!(
                s.contains(&format!("extension {t}: Decodable {{}}")),
                "{t} has no conformance"
            );
        }
        assert_eq!(s.matches(": Decodable {}").count(), TYPES.len());
        assert_eq!(
            s.matches("public init(from decoder: Decoder) throws {")
                .count(),
            TYPES.len()
        );
    }

    #[test]
    fn it_needs_no_runtime_but_foundation() {
        let s = generated();
        let imports: Vec<&str> = s.lines().filter(|l| l.starts_with("import ")).collect();
        assert_eq!(imports, ["import Foundation"]);
    }

    #[test]
    fn a_unit_variant_reads_a_bare_string() {
        let s = generated();
        assert!(s.contains("case \"Projects\": self = .projects"));
    }

    #[test]
    fn serde_renames_carry_over() {
        let s = generated();
        // Token is camelCase in JSON, LaneKey lower case.
        assert!(s.contains("case \"clayText\": self = .clayText"));
        assert!(s.contains("case \"unsorted\": self = .unsorted"));
    }

    #[test]
    fn a_struct_reads_its_rust_field_names() {
        let s = generated();
        assert!(s.contains("self.wsId = try c.req(\"ws_id\")"));
        assert!(s.contains("self.problem = try c.opt(\"problem\")"));
    }

    #[test]
    fn variants_with_payloads_read_one_key_objects() {
        let s = generated();
        assert!(s.contains("case \"Card\": self = .card(try c.req(\"Card\"))"));
        assert!(s.contains("case \"Ghost\":"));
        assert!(s.contains("case \"Lane\": self = .lane(try c.req(\"Lane\"))"));
    }

    #[test]
    fn it_starts_with_the_header() {
        assert!(generated().starts_with(HEADER));
    }
}
