//! The panel model's Swift types, generated from the Rust ones so the two
//! cannot drift. facet_generate writes the plain types; its own JSON mode
//! does not compile in Swift and Crux's generator is binary only (#254),
//! so `DecodablePlugin` adds an `init(from:)` to each type that reads
//! serde_json's default shapes, and a plain `JSONDecoder()` reads the
//! panel the sidebar's core hands back. The same file holds the core's
//! `Event` (#274), which the sidebar sends: `EncodablePlugin` adds an
//! `encode(to:)` to it and to every type it reaches, in the shapes serde
//! reads back, so a plain `JSONEncoder()` writes an event the core takes.
//! The panel's other types only decode: the Swift side never writes the
//! model.

mod decodable;
mod encodable;

use std::collections::BTreeSet;
use std::io;
use std::sync::Arc;

use cockpit_core::Event;
use cockpit_core::panel::Panel;
use facet::Facet;
use facet_generate::Registry;
use facet_generate::generation::CodeGeneratorConfig;
use facet_generate::generation::swift::SwiftCodeGenerator;
use facet_generate::reflection::RegistryBuilder;

pub use decodable::DecodablePlugin;
pub use encodable::EncodablePlugin;

/// The generated file's first line, so a reader knows not to edit it.
pub const HEADER: &str = "// Generated by native/typegen from the Rust panel model and events. Do not edit: run native/mac/test.sh or build.";

/// Why the Swift could not be written.
#[derive(Debug)]
pub enum Error {
    /// facet_generate could not reflect a type.
    Reflect(String),
    /// Writing the output failed.
    Io(io::Error),
    /// The generator wrote something other than UTF-8.
    Utf8(std::string::FromUtf8Error),
}

impl std::fmt::Display for Error {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Error::Reflect(e) => write!(f, "could not reflect the panel model: {e}"),
            Error::Io(e) => write!(f, "could not write the Swift: {e}"),
            Error::Utf8(e) => write!(f, "the Swift was not UTF-8: {e}"),
        }
    }
}

impl std::error::Error for Error {}

impl From<io::Error> for Error {
    fn from(e: io::Error) -> Self {
        Error::Io(e)
    }
}

/// The whole Swift file: every type `Panel` or `Event` reaches, each with
/// its `init(from:)`, and an `encode(to:)` on those `Event` reaches, then
/// their conformances.
pub fn swift() -> Result<String, Error> {
    swift_of::<Panel, Event>()
}

/// Every type `T` and `S` reach, as facet reflects them.
fn registry<'a, T: Facet<'a>, S: Facet<'a>>() -> Result<Registry, Error> {
    RegistryBuilder::new()
        .add_type::<T>()
        .and_then(RegistryBuilder::add_type::<S>)
        .and_then(RegistryBuilder::build)
        .map_err(|e| Error::Reflect(e.to_string()))
}

/// The Swift names of every type `S` reaches: the ones the shell sends.
fn sent<'a, S: Facet<'a>>() -> Result<BTreeSet<String>, Error> {
    let only = RegistryBuilder::new()
        .add_type::<S>()
        .and_then(RegistryBuilder::build)
        .map_err(|e| Error::Reflect(e.to_string()))?;
    Ok(only.keys().map(|k| k.name.clone()).collect())
}

/// The Swift file for `T`, read, and `S`, read and sent, with every type
/// they reach.
fn swift_of<'a, T: Facet<'a>, S: Facet<'a>>() -> Result<String, Error> {
    let registry = registry::<T, S>()?;
    let sent = sent::<S>()?;
    let config = CodeGeneratorConfig::new("PanelTypes".to_string());
    let mut out = Vec::new();
    SwiftCodeGenerator::new(&config)
        .with_plugins(vec![
            Arc::new(DecodablePlugin),
            Arc::new(EncodablePlugin { sent: sent.clone() }),
        ])
        .output(&mut out, &registry)?;
    let body = String::from_utf8(out).map_err(Error::Utf8)?;
    // The Swift emitter skips the plugin's conformance hook, so the
    // conformances go after the types, where the methods in each type's
    // body satisfy them.
    let conformances: String = registry
        .keys()
        .map(|k| {
            let kind = if sent.contains(&k.name) {
                "Codable"
            } else {
                "Decodable"
            };
            format!("extension {}: {kind} {{}}\n", k.name)
        })
        .collect();
    Ok(format!("{HEADER}\n\n{body}\n{conformances}"))
}

#[cfg(test)]
mod tests {
    use super::*;
    use cockpit_core::lanes::LaneKey;
    use cockpit_core::theme::Token;
    use facet_generate::reflection::format::ContainerFormat;

    /// Every type the panel reaches, as the Swift names them.
    const TYPES: [&str; 25] = [
        "Anchor",
        "Badge",
        "Card",
        "Chip",
        "ChipKind",
        "Density",
        "EditorView",
        "Icon",
        "Lane",
        "LaneKey",
        "MenuAction",
        "MenuItem",
        "MenuTarget",
        "MenuView",
        "Needs",
        "NeedsRow",
        "NextLine",
        "Panel",
        "PanelView",
        "Piece",
        "PillColors",
        "ProjectHead",
        "ProjectRow",
        "Row",
        "Token",
    ];

    fn generated() -> String {
        match swift() {
            Ok(s) => s,
            Err(e) => panic!("{e}"),
        }
    }

    /// Every type `Event` reaches, which the Swift both reads and writes.
    /// LaneKey and MenuAction the panel reaches too.
    const SENT: [&str; 5] = ["EditEvent", "Event", "LaneKey", "MenuAction", "MenuEvent"];

    #[test]
    fn every_type_the_panel_reaches_is_decodable() {
        let s = generated();
        for t in TYPES {
            let kind = if SENT.contains(&t) {
                "Codable"
            } else {
                "Decodable"
            };
            assert!(
                s.contains(&format!("extension {t}: {kind} {{}}")),
                "{t} has no conformance"
            );
        }
        let all = TYPES.len() + SENT.iter().filter(|t| !TYPES.contains(t)).count();
        assert_eq!(s.matches(": Decodable {}").count(), all - SENT.len());
        assert_eq!(
            s.matches("public init(from decoder: Decoder) throws {")
                .count(),
            all
        );
    }

    #[test]
    fn only_what_the_shell_sends_is_encodable() {
        let s = generated();
        for t in SENT {
            assert!(s.contains(&format!("extension {t}: Codable {{}}")), "{t}");
        }
        assert_eq!(s.matches(": Codable {}").count(), SENT.len());
        assert_eq!(
            s.matches("public func encode(to encoder: Encoder) throws {")
                .count(),
            SENT.len()
        );
    }

    #[test]
    fn events_write_serde_shapes() {
        let s = generated();
        assert!(s.contains("case .flipView: try encodeUnit(encoder, \"FlipView\")"));
        assert!(s.contains("case let .moveCard(f0, f1, f2):"));
        assert!(s.contains("forKey: SerdeKey(\"MoveCard\"))"));
        assert!(s.contains("try n.put(f2, \"before\")"));
        assert!(s.contains("case let .edit(f0):"));
        assert!(s.contains("try c.put(f0, \"Edit\")"));
        assert!(s.contains("case .main: try encodeUnit(encoder, \"main\")"));
    }

    #[test]
    fn at_holds_an_event_in_an_indirect_enum() {
        let s = generated();
        assert!(s.contains("indirect public enum Event: Hashable, Equatable {"));
        assert!(s.contains("case at(now: Double, event: Event)"));
    }

    /// Frames, state, projects and PR answers are left out of the Swift
    /// event: the shell does not send them yet, and their types are not
    /// reflected (they hold plain JSON maps).
    #[test]
    fn the_core_s_own_inputs_are_left_out() {
        let s = generated();
        for case in [
            "case data(",
            "case state(",
            "case projects(",
            "case prPolled(",
        ] {
            assert!(!s.contains(case), "{case}");
        }
        assert!(!s.contains("struct Data"));
        assert!(!s.contains("struct SavedState"));
    }

    #[test]
    fn it_needs_no_runtime_but_foundation() {
        let s = generated();
        let imports: Vec<&str> = s.lines().filter(|l| l.starts_with("import ")).collect();
        assert_eq!(imports, ["import Foundation"]);
    }

    #[test]
    fn a_unit_variant_reads_a_bare_string() {
        let s = generated();
        assert!(s.contains("case \"Projects\": self = .projects"));
    }

    #[test]
    fn serde_renames_carry_over() {
        let s = generated();
        // Token is camelCase in JSON, LaneKey lower case.
        assert!(s.contains("case \"clayText\": self = .clayText"));
        assert!(s.contains("case \"unsorted\": self = .unsorted"));
    }

    #[test]
    fn a_struct_reads_its_rust_field_names() {
        let s = generated();
        assert!(s.contains("self.wsId = try c.req(\"ws_id\")"));
        assert!(s.contains("self.problem = try c.opt(\"problem\")"));
    }

    #[test]
    fn variants_with_payloads_read_one_key_objects() {
        let s = generated();
        assert!(s.contains("case \"Card\": self = .card(try c.req(\"Card\"))"));
        assert!(s.contains("case \"Ghost\":"));
        assert!(s.contains("case \"Lane\": self = .lane(try c.req(\"Lane\"))"));
    }

    #[test]
    fn it_starts_with_the_header() {
        assert!(generated().starts_with(HEADER));
    }

    /// The JSON names facet gives `name`'s variants, which the Swift reads.
    fn variant_names(name: &str) -> Vec<String> {
        let registry = match registry::<Panel, Event>() {
            Ok(r) => r,
            Err(e) => panic!("{e}"),
        };
        let found = registry.iter().find(|(k, _)| k.name == name);
        match found {
            Some((_, ContainerFormat::Enum(variants, _, _))) => {
                variants.values().map(|v| v.name.clone()).collect()
            }
            _ => panic!("{name} is not an enum the panel reaches"),
        }
    }

    /// Token and LaneKey carry their rename twice, for serde and for facet.
    /// serde must accept every name facet hands the Swift, or a frame with
    /// that token would fail to decode.
    #[test]
    fn facet_and_serde_rename_alike() {
        let tokens = variant_names("Token");
        assert!(tokens.len() > 30, "{tokens:?}");
        for v in tokens {
            let read: Result<Token, _> = serde_json::from_str(&format!("\"{v}\""));
            assert!(read.is_ok(), "serde has no Token named {v}");
        }
        let lanes = variant_names("LaneKey");
        assert_eq!(lanes.len(), 5);
        for v in lanes {
            let read: Result<LaneKey, _> = serde_json::from_str(&format!("\"{v}\""));
            assert!(read.is_ok(), "serde has no LaneKey named {v}");
        }
    }

    #[derive(facet::Facet)]
    struct Wrapped(String);

    #[derive(facet::Facet)]
    struct HoldsWrapped {
        id: Wrapped,
    }

    #[derive(facet::Facet)]
    #[repr(u8)]
    enum HasTuple {
        Pair(String, u8),
    }

    fn refused(r: Result<String, Error>) -> String {
        match r {
            Ok(_) => panic!("generated Swift for a shape it cannot read"),
            Err(e) => e.to_string(),
        }
    }

    #[test]
    fn a_tuple_struct_fails_the_generator() {
        let held = HoldsWrapped {
            id: Wrapped("ws".into()),
        };
        assert_eq!(held.id.0, "ws");
        assert!(
            refused(swift_of::<HoldsWrapped, HoldsWrapped>()).contains("Wrapped, a tuple struct")
        );
    }

    #[test]
    fn a_tuple_variant_fails_the_generator() {
        let HasTuple::Pair(s, n) = HasTuple::Pair("a".into(), 1);
        assert_eq!((s.as_str(), n), ("a", 1));
        assert!(refused(swift_of::<HasTuple, HasTuple>()).contains("variant Pair"));
    }
}
