import Foundation

/// One of Jon's actions, as the sidebar sends it to its own core
/// (Live/SidebarCore.swift): the core's own `Event`, generated by
/// native/typegen with an `encode(to:)` that writes serde's externally
/// tagged shapes, so `.flipView` is `"FlipView"`, `.switchTo(id:)` is
/// `{"SwitchTo": {"id": "W1"}}` and `.menu(.close)` is `{"Menu": "Close"}`.
/// Only the actions among them are clicks (`isAction`); the rest are the
/// shell's own inputs. native/core/tests/actions.json holds one file per
/// action, which the Rust and the Swift checks both read.
typealias SidebarAction = Event

extension Event {
    /// The core's `EditEvent`, by the name the views use.
    typealias Edit = EditEvent
    /// The core's `MenuEvent`, by the name the views use.
    typealias Menu = MenuEvent

    /// A click on a lane's heading, unlabelled as the views spell it.
    static func toggleLane(_ lane: LaneKey) -> Event { .toggleLane(lane: lane) }

    /// Whether it is one of Jon's clicks, as the core's `is_action` sorts
    /// them, rather than one of the shell's own inputs; `At` is the stamp
    /// the sidebar puts on a click, never a click itself. A switch with no
    /// default, so a new event fails to compile here until it is sorted.
    var isAction: Bool {
        switch self {
        case .refresh, .home, .cmuxFailed, .prPollOn, .panelOn, .at: false
        case .moveCard, .switchTo, .selected, .dismiss, .flipView, .edit, .openProject,
             .fileForReview, .parkMerged, .closeMerged, .keepMerged, .menu, .next,
             .messageAgent, .toggleLane, .toggleProject, .toggleQuiet, .reveal:
            true
        }
    }
}

extension SidebarAction {
    /// The core's words on a merged card's two buttons (panel/mod.rs
    /// PARK and CLOSE): the chip says which one it is.
    static let parkWord = "Park"
    static let closeWord = "Close"

    /// What tapping one of a card's merged chips sends: Park or Close, by
    /// its words. The core puts Close there only where it offers it, and
    /// checks again when the action lands.
    static func merged(_ chip: Chip, id: String) -> SidebarAction? {
        switch chip.pieces.first?.text {
        case parkWord: .parkMerged(id: id)
        case closeWord: .closeMerged(id: id)
        default: nil
        }
    }

    /// What picking an item of a card's menu sends: the menu opened on
    /// that card, then the item, in that order, as the pane's Space then
    /// Enter would.
    static func pick(_ action: MenuAction, on id: String) -> [SidebarAction] {
        [.menu(.openCard(id: id)), .menu(.pick(action))]
    }

    /// "Message agent…" sends only words: blank text sends nothing.
    static func message(_ text: String, to id: String) -> SidebarAction? {
        let words = text.trimmingCharacters(in: .whitespacesAndNewlines)
        return words.isEmpty ? nil : .messageAgent(id: id, text: words)
    }
}
